import { ICard } from '../types/types';

export const images: { [key: string]: ICard[] } = {
  superheroes: [
    { src: '/heroes/batman.png', id: 1, isActive: false },
    { src: '/heroes/batman.png', id: 2, isActive: false },
    { src: '/heroes/black_widow.png', id: 3, isActive: false },
    { src: '/heroes/black_widow.png', id: 4, isActive: false },
    { src: '/heroes/captain_america.png', id: 5, isActive: false },
    { src: '/heroes/captain_america.png', id: 6, isActive: false },
    { src: '/heroes/deadpool.png', id: 7, isActive: false },
    { src: '/heroes/deadpool.png', id: 8, isActive: false },
    { src: '/heroes/dr_strange.png', id: 9, isActive: false },
    { src: '/heroes/dr_strange.png', id: 10, isActive: false },
    { src: '/heroes/flash.png', id: 11, isActive: false },
    { src: '/heroes/flash.png', id: 12, isActive: false },
    { src: '/heroes/hulk.png', id: 13, isActive: false },
    { src: '/heroes/hulk.png', id: 14, isActive: false },
    { src: '/heroes/iron_man.png', id: 15, isActive: false },
    { src: '/heroes/iron_man.png', id: 16, isActive: false },
    { src: '/heroes/jocker.png', id: 17, isActive: false },
    { src: '/heroes/jocker.png', id: 18, isActive: false },
    { src: '/heroes/pantera.png', id: 19, isActive: false },
    { src: '/heroes/pantera.png', id: 20, isActive: false },
    { src: '/heroes/reccon.png', id: 21, isActive: false },
    { src: '/heroes/reccon.png', id: 22, isActive: false },
    { src: '/heroes/spider_man.png', id: 23, isActive: false },
    { src: '/heroes/spider_man.png', id: 24, isActive: false },
    { src: '/heroes/superman.png', id: 25, isActive: false },
    { src: '/heroes/superman.png', id: 26, isActive: false },
    { src: '/heroes/tor.png', id: 27, isActive: false },
    { src: '/heroes/tor.png', id: 28, isActive: false },
    { src: '/heroes/venom.png', id: 29, isActive: false },
    { src: '/heroes/venom.png', id: 30, isActive: false },
    { src: '/heroes/wolverine.png', id: 31, isActive: false },
    { src: '/heroes/wolverine.png', id: 32, isActive: false },
  ],
};
