import { ICard } from '../types/types';

export const images: { [key: string]: ICard[] } = {
  cars: [
    { src: '/cars/black-ds.png', id: 1, isActive: false },
    { src: '/cars/black-ds.png', id: 2, isActive: false },
    { src: '/cars/black-toyota.png', id: 3, isActive: false },
    { src: '/cars/black-toyota.png', id: 4, isActive: false },
    { src: '/cars/black-mers.png', id: 5, isActive: false },
    { src: '/cars/black-mers.png', id: 6, isActive: false },
    { src: '/cars/blue-bmw.png', id: 7, isActive: false },
    { src: '/cars/blue-bmw.png', id: 8, isActive: false },
    { src: '/cars/grey-bmw.png', id: 9, isActive: false },
    { src: '/cars/grey-bmw.png', id: 10, isActive: false },
    { src: '/cars/orange-hundai.png', id: 11, isActive: false },
    { src: '/cars/orange-hundai.png', id: 12, isActive: false },
    { src: '/cars/orange-rover.png', id: 13, isActive: false },
    { src: '/cars/orange-rover.png', id: 14, isActive: false },
    { src: '/cars/police-car.png', id: 15, isActive: false },
    { src: '/cars/police-car.png', id: 16, isActive: false },
    { src: '/cars/red-audi.png', id: 17, isActive: false },
    { src: '/cars/red-audi.png', id: 18, isActive: false },
    { src: '/cars/red-wol.png', id: 19, isActive: false },
    { src: '/cars/red-wol.png', id: 20, isActive: false },
    { src: '/cars/strange-car.png', id: 21, isActive: false },
    { src: '/cars/strange-car.png', id: 22, isActive: false },
    { src: '/cars/white-audi.png', id: 23, isActive: false },
    { src: '/cars/white-audi.png', id: 24, isActive: false },
    { src: '/cars/white-lambo.png', id: 25, isActive: false },
    { src: '/cars/white-lambo.png', id: 26, isActive: false },
    { src: '/cars/white-mersedec.png', id: 27, isActive: false },
    { src: '/cars/white-mersedec.png', id: 28, isActive: false },
    { src: '/cars/yellow-ford.png', id: 29, isActive: false },
    { src: '/cars/yellow-ford.png', id: 30, isActive: false },
    { src: '/cars/grey-supercar.png', id: 31, isActive: false },
    { src: '/cars/grey-supercar.png', id: 32, isActive: false },
  ],
};
