import { Injectable, signal } from '@angular/core';
import { Figure } from '../classes/figure';
import { Board, Color, FigureEnum, GameType } from '../types';

@Injectable({
  providedIn: 'root',
})
export class ChessService {
  public board;
  public gameType = signal<GameType | null>('bot');
  constructor() {
    this.board = signal<Board[]>([
      new Figure(FigureEnum.ROOK, Color.BLACK, [0, 0]),
      new Figure(FigureEnum.KNIGHT, Color.BLACK, [0, 1]),
      new Figure(FigureEnum.BISHOP, Color.BLACK, [0, 2]),
      new Figure(FigureEnum.QUEEN, Color.BLACK, [0, 3]),
      new Figure(FigureEnum.KING, Color.BLACK, [0, 4]),
      new Figure(FigureEnum.BISHOP, Color.BLACK, [0, 5]),
      new Figure(FigureEnum.KNIGHT, Color.BLACK, [0, 6]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [0, 7]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 0]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 1]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 2]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 3]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 4]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 5]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 6]),
      new Figure(FigureEnum.PAWN, Color.BLACK, [1, 7]),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new Figure(FigureEnum.ROOK, Color.WHITE, [6, 0]),
      new Figure(FigureEnum.KNIGHT, Color.WHITE, [6, 1]),
      new Figure(FigureEnum.BISHOP, Color.WHITE, [6, 2]),
      new Figure(FigureEnum.QUEEN, Color.WHITE, [6, 3]),
      new Figure(FigureEnum.KING, Color.WHITE, [6, 4]),
      new Figure(FigureEnum.BISHOP, Color.WHITE, [6, 5]),
      new Figure(FigureEnum.KNIGHT, Color.WHITE, [6, 6]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [6, 7]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 0]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 1]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 2]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 3]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 4]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 5]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 6]),
      new Figure(FigureEnum.PAWN, Color.WHITE, [7, 7]),
    ]);
  }
}
